### ISSUE TITLE
Vdebug spams my buffer list.

### ISSUE THREAD

**Issue by trq** [joonty/vdebug#117]
When executing a debugging session using Vdebug all files that have been opened during the session remain in the buffer list for the remainder of my vim session.

it would be nice if these where closed automatically for me so that they don't get in the way of my workflow.

I know if these files where opened with a specific filetype I could close them using something like:

```
autocmd BufReadPost vdebug://* set bufhidden=delete
```

See **auto clean buffers** [here](http://vimcasts.org/episodes/fugitive-vim-browsing-the-git-object-database).

But I'm not real sure how to implement that with Vdeug.

**Comment by mikewhitby** [comment]
+1
Would it also be possible to remove the others windows i.e. watch from the buffer list using `nobuflisted`?
