### ISSUE TITLE
vdebug doesn't ignore ide key when debugging nodejs code

### ISSUE THREAD

**Issue by mahmoudelbadry** [joonty/vdebug#146]
when running komodo-debug, vdebug ignore the connection because it's ide key is empty, and komodo-debug doesn't have and ide key setting (that I know of)

for now I use this command 

```
let g:vdebug_options["ide_key"] = ""
```

**Comment by joonty** [comment]
Just to clarify, setting a blank IDE key (which is the default) means that Vdebug will accept *all* incoming connections - i.e. it doesn't compare the IDE key at all.

I may be misunderstanding this still, so please let me know if I am!

Thanks
