### ISSUE TITLE
Breakpoints 2 way mapping

### ISSUE THREAD

**Issue by exussum12** [joonty/vdebug#152]
Not sure if its something i should be doing different but, I have 2 path maps set to the same local path (ie /var/place1 maps to /home/user/place and /ebs/place2/ also maps to /home/user/place)

This works fine when loading up and stepping though code etc, But when Breakpoints are added, They only work on /var/place1

/place1 and /place2 are the difference between a live and dev machine, and share the same code. They are mounted over sshfs.

Looking at the code for the beakpoints, only 1 breakpoint is applied when asked to be set, The first one defined. meaning /place2's breakpoint for the same file is never set.

Is there a reason why the breakpoint code breaks and returns when its found the first ? or could it carry on and set on for all matching paths ?

**Comment by BlackIkeEagle** [comment]
I think this will be very flaky and will lead to more issues than you want to solve. I suggest you use a tool like vimsauce to specify your project and set the vdebug path mapping there.
