### ISSUE TITLE
Server cannot connect back to client?

### ISSUE THREAD

**Issue by chrisnojima** [joonty/vdebug#165]
Hi,

I'm debugging against a remote host (PHP) and i see in my logs the following:

I: Checking remote connect back address.
I: Remote address found, connecting to xxx.xxx.xxx.xxx:9001,
E: Could not connect to client. :-(

This means I can start a debugging session and can step but when I run I cannot get breakpoints or xdebug_break calls to stop. I tried setting this up with eclipse and phpstorm and both of those clients successfully handle the remote connect back correctly (and breakpoints, etc) which implies that connectivity is working (vdebug fails with mac os firewall turned off etc).

Any ideas why this would happen?

**Comment by serundeputy** [comment]
@chrisnojima @joonty did you folks get this working? I'm trying to use vdebug via ssh tunnel.

**Comment by chrisnojima** [comment]
Sorry I don't use this anymore

**Comment by przepompownia** [comment]
@serundeputy maybe details about tunnel configuration are needed to help you by anyone.

**Comment by serundeputy** [comment]
I'm using `neovim` w/ `vdebug`: https://github.com/serundeputy/gffNeovim/blob/master/gff.init.vim#L182

Connecting to a remote host on platform.sh using `lando platform xdebug` like so https://docs.platform.sh/languages/php/xdebug.html

This opens a tunnel on port 9000:

```bash
gff ~/code/tandem/clmp/clmp 
(28/adoption) └─ ∴ lando platform xdebug -e pr-37
Opening a local tunnel for Xdebug.

Xdebug tunnel opened at: 127.0.0.1:9000

To start debugging, set a cookie like 'XDEBUG_SESSION=vdebug' or append 'XDEBUG_SESSION_START=vdebug' in the URL query string when visiting your project.

To close the tunnel, quit this command by pressing Ctrl+C.
To change the local port, re-run this command with the --port option.

```

I'm not sure if i need addtional `vdebug` config in my `init.vim` if you spot anything amiss i would appreciate it.

**Comment by przepompownia** [comment]
It still does not seem to reveal (anonymized) enough details how do you create port forwarding by your SSH client. Your VDebug probably listens on the default port 9000 on all interfaces of your local machine. If so, you did not explain how your remote machine can achieve port 9000 on your local machine. 

Probably at least one remote port forwarding can be needed (unless your local machine is accessible from the remote in another way).

Your XDebug configuration also can be needed: both from ini file and from environment variable if you provide it with any shell or the cookie.

**Comment by serundeputy** [comment]
thanks. 

I'm in over my head. `psysh` is good enough for me to solve my current problem (although slightly painful).

thanks for the help.
