### ISSUE TITLE
Help chapter 6 Key Maps wrong default run_to_cursor

### ISSUE THREAD

**Issue by SunMar** [joonty/vdebug#172]
Hi, great plugin! When reading the help though I discovered that in chapter 6 the default keymap show for run_to_cursor doesn't correspond with the default in vdebug.vim. In the help it says F1 but in vdebug.vim it's F9. Possibly the keymap was changed at some point? Thnx! :)

**Comment by joonty** [comment]
Resolved in `dev`, will be released in 1.5.0. Thanks!
