### ISSUE TITLE
Watch window - no indication when an array has not sent all its elements

### ISSUE THREAD

**Issue by bgardner-noggin** [joonty/vdebug#177]
XDebug will only send through 31 elements of an array, although the size of the array is indicated at the next to the variable name, there is no indication at the bottom of the children that not all children have been shown

The attached patch adds an indicator 

 ▾ $foo = (array [50]) 
  \
   ⬦ $foo[0] = (int) 0
   |
   ⬦ $foo[1] = (int) 1
   |
   ⬦ $foo[2] = (int) 2
   |
   ⬦ $foo[3] = (int) 3
   |
   ⬦ $foo[4] = (int) 4
   |
   ⬦ $foo[5] = (int) 5
   |
   ⬦ $foo[6] = (int) 6
   |
   ⬦ $foo[7] = (int) 7
   |
   ⬦ $foo[8] = (int) 8
   |
   ⬦ $foo[9] = (int) 9
   |
   ⬦ $foo[10] = (int) 10
   |
   ⬦ $foo[11] = (int) 11
   |
   ⬦ $foo[12] = (int) 12
   |
   ⬦ $foo[13] = (int) 13
   |
   ⬦ $foo[14] = (int) 14
   |
   ⬦ $foo[15] = (int) 15
   |
   ⬦ $foo[16] = (int) 16
   |
   ⬦ $foo[17] = (int) 17
   |
   ⬦ $foo[18] = (int) 18
   |
   ⬦ $foo[19] = (int) 19
   |
   ⬦ $foo[20] = (int) 20
   |
   ⬦ $foo[21] = (int) 21
   |
   ⬦ $foo[22] = (int) 22
   |
   ⬦ $foo[23] = (int) 23
   |
   ⬦ $foo[24] = (int) 24
   |
   ⬦ $foo[25] = (int) 25
   |
   ⬦ $foo[26] = (int) 26
   |
   ⬦ $foo[27] = (int) 27
   |
   ⬦ $foo[28] = (int) 28
   |
   ⬦ $foo[29] = (int) 29
   |
   ⬦ $foo[30] = (int) 30
   |
   ⬦ $foo[31] = (int) 31
   |
   ...

**Comment by lkraav** [comment]
Did this ever get anywhere? I'm also noticing there's only a few array items shown out of a much bigger set.

**Comment by bgardner-noggin** [comment]
The problem is that XDebug does not send the information, at least for PHP.
So the best we can do is display a marker that there was more information
and then you go back to the old fashioned dump statement.

On Thu, Jan 15, 2015 at 9:39 AM, Leho Kraav <notifications@github.com>
wrote:

> Did this ever get anywhere? I'm also noticing there's only a few array
> items shown out of a much bigger set.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joonty/vdebug/issues/177#issuecomment-70007029>.
>



-- 
  [image: Noggin IT Logo]
<http://www.nogginoca.com?utm_source=Email-Signature&utm_medium=Email-Signature&utm_campaign=Email-Signature?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>
   Brett Gardner •Technical lead  Noggin IT  t 02 9219 8808 m 0412 940 256
e bgardner@noggin.com.au w www.nogginoca.com
<http://www.nogginoca.com?utm_source=Email-Signature&utm_medium=Email-Signature&utm_campaign=Email-Signature?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>
 a Level 30, 175 Liverpool Street, Sydney, NSW, Australia, 2000  [image:
Facebook] <http://www.facebook.com/nogginIT> [image: Twitter]
<http://www.twitter.com/nogginoca> [image: Linkedin]
<http://www.linkedin.com/company/noggin-it> [image: Were Hiring]
<https://boards.greenhouse.io/nogginit#.VHJvj5PF8oR>  [image: Manage Risk
In The Real World With Noggin OCA]
<http://www.nogginoca.com/products/oca-product-suite/oca-risk.html?utm_source=Email-Signature&utm_medium=Email-Signature&utm_campaign=Email-Signature?utm_source=Email-Signature-Rescue&utm_medium=Email-Signature&utm_campaign=Email-Signature-Rescue>

**Comment by joonty** [comment]
Merged! It's a Christmas miracle!

Sorry it's taken so long. Thanks @bgardner-noggin for the patch, and @lkraav for giving me a shove.

Allow me to refer you to this: http://blog.joncairns.com/2015/01/looking-for-another-vdebug-maintainer/
