### ISSUE TITLE
DebuggerStatus: Only ten visible elements in Perl hash or list that is greater

### ISSUE THREAD

**Issue by crayday** [joonty/vdebug#183]
Thank you very much for such a nice experience with Vim and Perl!

However I've encountered some problems. When I'm expanding hash or list in DebuggerStatus window, I can see only ten elements, even if there're more. It look's like this:

```
 ⬦ $AdditionalData = (array)
 ▾ $ArtProp = (hash [53])
   ⬦ $ArtProp->{adult} = (scalar [2]) `12`
   ⬦ $ArtProp->{adult_annotation} = (scalar [1]) `0`
   ⬦ $ArtProp->{adult_cover} = (scalar [1]) `0`
   ⬦ $ArtProp->{allow_drm} = (scalar [1]) `0`
   ⬦ $ArtProp->{allow_online_reading} = (scalar [1]) `0`
   ⬦ $ArtProp->{art_age} = (scalar [8]) `180.6633`
   ⬦ $ArtProp->{'author-name'} = (scalar [17]) `Макс Фрай`
   ⬦ $ArtProp->{'author-name-dateln'} = (scalar [19]) `Максу Фраю`
   ⬦ $ArtProp->{'author-name-predl'} = (scalar [19]) `Максе Фрае`
   ⬦ $ArtProp->{'author-name-rodit'} = (scalar [19]) `Макса Фрая`
 ⬦ $ID = (scalar [7]) `6689025`
```

In this example hash consists of 53 elements but I can view only 10 of them.

I don't know, maybe this is not a problem with Vdebug. Can you please give any advice on solving this problem or confirm it as a bug?

Sorry for my russian-english.

**Comment by joonty** [comment]
This is ridiculously late, but you can use `xdebug.var_display_max_children` to change the number of array children returned by Xdebug. But it should default to 128, so I don't know why it's being random @exussum12. Try setting that var explicitly, and seeing whether that makes any difference.
