### ISSUE TITLE
vim .swp files prevent debugging from starting - error: Vim(new):E325 - 

### ISSUE THREAD

**Issue by rlittlefield** [joonty/vdebug#187]
When vim has .swp files, it generates an error that prevents vdebug from opening the file at the first line (or anywhere with a bad file). The error I get is "error: Vim(new):E325", preceded by a python stack trace.

This can be tested by killing the vim processing during debugging or editing a file. If that file needs to be opened to show the current line of execution, the status line shows:

Waiting for a connection (Ctrl-C to cancel, this message will self-destruct in  20  seconds...)

And as soon as you connect, the message persists, but the cursor appears at the end of the line. Normally the cursor is not visible while waiting for a connection. In actuality, the connection has been established and vdebug is trying to open the first file. Pressing enter will show the error message above. This can be resolved manually by exiting vim and removing the .swp files (several of which vdebug appears to make), or by opening them in vim manually and choosing how to resolve the .swp issue.

**Comment by joonty** [comment]
I've had a good look at this, and I'm pretty sure there's not a decent solution until I can introduce version 2, which uses non-blocking listening. It looks like Vim's UI doesn't recover well after the "Waiting for a connection" phase, and sometimes output gets lost.

I've tagged it with version 2's milestone, and will tackle it then - hopefully it will be a simpler fix then.

**Comment by dkinzer** [comment]
:+1:

**Comment by benjifisher** [comment]
I am not sure whether I am seeing the same problem or a related one.  Are you talking about swap files for the code you are editing or for the debugger windows?

I notice that swap files like `.DebuggerWatch.swp` cause problems when something kills vim.  (Typically the battery on my laptop runs out or something:  not the fault of vim nor vdebug!)  There are already lines

```python
    def create(self):
        """ create window """
        vim.command('silent ' + self.open_cmd + ' ' + self.name)
        vim.command("setlocal buftype=nofile modifiable "+ \
                "winfixheight winfixwidth")
```

in `python/vdebug/ui/vimui.py`.  You might think that would be enough to prevent the swap files from being created, but if you read the docs carefully (and test) you will see (under `:help 'buftype'`)

```
	"nofile" and "nowrite" buffers are similar:
...
	both:		A swap file is only created when using too much memory
```

The problem is that setting `buftype=nofile` after the buffer has been created is too late:  the swap file is already there, and it is not deleted.  The solution is to add the `:noswapfile` modifier:

```python
    def create(self):
        """ create window """
        vim.command('silent noswapfile ' + self.open_cmd + ' ' + self.name)
        vim.command("setlocal buftype=nofile modifiable "+ \
                "winfixheight winfixwidth")
```

I need to test this further, but so far I think it is an improvement.

**Comment by joonty** [comment]
Thanks @benjifisher for looking into this, that's really helpful! I'll have a play around with it when I can.

**Comment by mmikitka** [comment]
+1 I am also encountering this behaviour.

**Comment by benjifisher** [comment]
@mmikitka :  Did you try the fix I suggested?  I can create a PR if you like, but it is just a matter of changing `'silent '` to `'silent noswapfile '` (note the trailing spaces).

**Comment by BlackIkeEagle** [comment]
@benjifisher you could create a PR anyway because the Vdebug windows do not need swapfiles

**Comment by mmikitka** [comment]
@benjifisher I applied your patch, and swap files are not generated for the Debugger* buffers, however I do not receive swap file notifications for files opened by VDebug during the debugging process (I may or may not be editing these files). The two solutions to this problem are: (1) manually check and delete buffers after a crash; (2) when VDebug starts, load all net-new buffers with noswapfile (i.e., files that were not open before starting the debugger).

Nonetheless, merging this patch is still desirable, in my opinion.

Note, however, that I do receive swap file warnings in gvim; only in console vim do I not see the notifications.

And, for those wanting to reproduce the problem, send a "kill -9" signal to the vim process to ensure that vim does not invoke the swap file cleanup routines.

**Comment by BlackIkeEagle** [comment]
This fix is added in the v2-integration branch, thanks

**Comment by benjifisher** [comment]
@BlackIkeEagle Thanks for working on this.  I apologize for not following up and submitting a PR.
