### ISSUE TITLE
Need informative error messages when vim lacks +python

### ISSUE THREAD

**Issue by ReekenX** [joonty/vdebug#192]
I really love your plugin - can't live a day without using it!

It worked great until on latest Ubuntu version, with latest VIM I installed vim-gtk plugin which adds +clipboard and +xterm_clipboard support to VIM. Vdebug stopped working, I don't see any errors nor I can access any "let g:vdebug_options". Also pressing <F5> and any other doesn't bring any messages like "waiting for connection".

After `apt-get purge vim-gtk` and closing and opening VIM, I see vdebug working: pressing <F5> shows "waiting for connection".

Installed vim-gnome (which gives +clipboard) too, vdebug doesn't work as before. Works as soon as I remove it: `apt-get purge vim-gnome`.

All my configuration is public and available here: https://github.com/ReekenX/dotfiles

How can I help to debug this issue?

**Comment by lucc** [comment]
#294 is essentially the same problem. I did not see this discussion here so I opened #297. 

The readme file already states that vim needs python2 support (see line 88). So maybe this can be closed?

**Comment by BlackIkeEagle** [comment]
This seems fixed in v2-integration
