### ISSUE TITLE
E887: Sorry, this command is disabled, the Python's site module could not be loa ded.

### ISSUE THREAD

**Issue by arcticlion** [joonty/vdebug#195]
Error detected while processing /Users/MasterMac/dotfile/.vim/bundle/vdebug/plugin/vdebug.vim:
line   40:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
line  111:
E887: Sorry, this command is disabled, the Python's site module could not be loaded.
Press ENTER or type command to continue

**Comment by joonty** [comment]
Hi, it looks like this is an issue with the Python version that your vim is compiled with. Take a look at [this issue](https://github.com/yyuu/pyenv/issues/234). Are you using MacVim, and is it installed through homebrew?

Thanks

**Comment by arcticlion** [comment]
Yes, I install vim through homebrew and python version is 2.7.9



在 2015年1月30日 下午10:40:33, Jonathan Cairns (notifications@github.com) 写到:

Hi, it looks like this is an issue with the Python version that your vim is compiled with. Take a look at this issue. Are you using MacVim, and is it installed through homebrew?

Thanks

**Comment by arcticlion** [comment]
It work when i reinstall vim.



在 2015年1月30日 下午10:40:33, Jonathan Cairns (notifications@github.com) 写到:

Hi, it looks like this is an issue with the Python version that your vim is compiled with. Take a look at this issue. Are you using MacVim, and is it installed through homebrew?

Thanks

**Comment by joonty** [comment]
Great :)
