### ISSUE TITLE
Trouble connecting to remote server

### ISSUE THREAD

**Issue by toddbranch** [joonty/vdebug#198]
Thanks for all your work on this plugin!

I'm having trouble connecting to a remote server.  Using xdebug's debugclient, I can easily connect - which makes me think things are setup properly.  When I try to connect using vdebug, it just hangs.  I am able to successfully debug scripts on my locale machine.

**Comment by toddbranch** [comment]
Here's the output of my debugclient, if that helps:
Waiting for debug server to connect.
Connect
<?xml version="1.0" encoding="iso-8859-1"?>
<init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///mnt/nfs3/dev-env/tbranchflower/www/virtual/mywedding/current/mywedding/application/bootstrap/bootstrap.php" language="PHP" protocol_version="1.0" appid="4985" idekey="XDEBUG_ECLIPSE"><engine version="2.2.3"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2013 by Derick Rethans]]></copyright></init>

**Comment by toddbranch** [comment]
This was me - read the instructions in more detail and problem was fixed!  I had localhost as my server, vice my own IP

**Comment by joonty** [comment]
Nice one! Sorry I couldn't get to you quicker. Glad you managed to sort it.
