### ISSUE TITLE
Inconsistent behaviour when using multiple path mappings

### ISSUE THREAD

**Issue by adambiggs** [joonty/vdebug#199]
Took me a while to figure out what was going on here...

I'm trying to debug a Wordpress app, with a custom theme and plugin at the same level on my host machine as the repo containing the Wordpress source. On the server, the theme and plugin files are copied *inside* the wordpress source (in a Docker image).

So I had my path mappings set up similar to this:

```vim
let g:vdebug_options['path_maps'] = {
\  "/var/www/html": "/Users/adam/Repos/wordpress",
\  "/var/www/html/wp-content/plugins/lmpm-wp-plugin": "/Users/adam/Repos/wordpress-plugin",
\  "/var/www/html/wp-content/themes/lmpm-wp-theme": "/Users/adam/Repos/wordpress-theme"
\ }
```

But I noticed that the more general mapping was *sometimes* conflicting with the more specific ones, resulting in paths like this:
```
/Users/adam/Repos/wordpress/wp-content/plugins/wordpress-plugin/some-file.php
```

But sometimes it worked fine... It looked like the more specific paths needed to come first, followed by the more general ones. So I tried organizing the dictionary as such:

```vim
let g:vdebug_options['path_maps'] = {
\  "/var/www/html/wp-content/plugins/lmpm-wp-plugin": "/Users/adam/Repos/wordpress-plugin",
\  "/var/www/html/wp-content/themes/lmpm-wp-theme": "/Users/adam/Repos/wordpress-theme",
\  "/var/www/html": "/Users/adam/Repos/wordpress"
\ }
```

... Which seemed to fix the problem in some cases, but create the same problem in other places! After pulling out some hair, I came across an interesting note near the bottom of [this page](http://learnvimscriptthehardway.stevelosh.com/chapters/37.html):

> As far as I can tell Vimscript dictionaries are not guaranteed to be ordered, so don't expect that the items you get out of an items call will be in a specific order!

Sure enough, `:let g:vdebug_options['path_maps']` shows the dictionary in a different order than it was defined...

So while I think I might have found a solution to the problem, I have no idea how to implement it :cry:

**Comment by joonty** [comment]
Resolved, see #201
