### ISSUE TITLE
Can't set g:vdebug_options from .vimrc

### ISSUE THREAD

**Issue by bitwombat** [joonty/vdebug#200]
Non-vim programmers might put this in their vimrc:

`let g:vdebug_options['port']=10000`

But they'd get this from vim:

```
Error detected while processing /home/gbell2/.vimrc:
line  255:
E121: Undefined variable: g:vdebug_options
```

Solution is to create the dict before it's used:
`let g:vdebug_options={}
let g:vdebug_options['port']=10000`

It would be good to have a note about that in section 5.2 of the docs.

**Comment by jrean** [comment]
I had the same issue!
Thank you very much for the workaround.

**Comment by mikebarkas** [comment]
I also received that error trying to set just one option.

My solution was this:

`let g:vdebug_options = { "port" : 10000 }`

And then to set a multiple options:

    let g:vdebug_options = {
    \    "port" : 10000,
    \    "break_on_open" : 0,
    \}

**Comment by Taluu** [comment]
I'm currently using this to get by this problem ;

```vim
      if !exists('g:vdebug_options')
            let g:vdebug_options = {}
        endif

        " let g:vdebug_options["break_on_open"] = 0
        let g:vdebug_options["watch_window_height"]=45
        let g:vdebug_options["status_window_height"]=5
        " let g:vdebug_options["continuous_mode"]=1
```

**Comment by jrean** [comment]
@Taluu, I did quite the same!
I just didn't check if the variable exists.
`let g:vdebug_options={}`

I'll add the test too :)

**Comment by joonty** [comment]
I've looked at this issue a few times, but it definitely needs a definitive solution, even if it is a documentation thing. I'll have a look into it, but if anyone has any bright ideas then please share them!

Thanks

**Comment by IWriteThings** [comment]
autocmd VimEnter * VdebugOpt server 192.168.50.1
autocmd VimEnter * VdebugOpt port 9001

You can add the above to your .vimrc in order to run commands AFTER everything is loaded. This allows you to easily change the settings inside VIMRC without making new files, checking for variables, or anything of the sort.

**Comment by dyong0** [comment]
+1

**Comment by lucc** [comment]
I think the only solution here is to update the docs. I would be happy to send a PR for this but I found that the docs are inconstent on the variable names. At some point vdebug_options is a dict and later several variables vdebug_options_port and so on are mentioned. 

I think the latter is a relict and also needs to be updated.  If you can confirm this I will send the PR.

**Comment by lucc** [comment]
Was #278 enough to solve this? Do we need to do something else?

**Comment by BlackIkeEagle** [comment]
@lucc that was indeed sufficient
