### ISSUE TITLE
[Node] TypeError exception on get_id

### ISSUE THREAD

**Issue by irbrad** [joonty/vdebug#202]
I'm getting a TypeError exception when trying to debug a Node script using _Vdebug_ and _node-dbgp_. I've already debugged Python scripts so I know that at least that language is working.  

This looks similar to [vdebug#156](https://github.com/joonty/vdebug/issues/156) but that issue was closed without any useful information.

Steps to reproduce:

1. `npm install -g komodo-debug`
2. *F10* to set a breakpoint on line 2 of test.js (provided below).
3. *F5* to start debugging.
4. Switch to another terminal and run ` /usr/local/bin/node-dbgp -h 127.0.0.1 -p 9000 ~/test.js`

Error:

```
An error occured: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "~/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "~/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 160, in run
    self.open()
  File "~/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 60, in open
    self.breakpoints.link_api(self.api)
  File "~/.vim/bundle/vdebug/plugin/python/vdebug/breakpoint.py", line 17, in link_api
    bp.set_debugger_id(res.get_id())
  File "~/.vim/bundle/vdebug/plugin/python/vdebug/dbgp.py", line 150, in get_id
    return int(self.as_xml().get('id'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

test.js:

```javascript
var foo = 'bar';
console.log('foo' + foo);
```

**Comment by joonty** [comment]
Hi @irbrad,

Sorry about the delay on this. I'll try and reproduce this as soon as I can. I've had numerous problems trying to get the ActiveState debuggers working, as they don't follow the dbgp protocol *that* faithfully.

I'll get back to you as soon as I can.

Thanks

**Comment by joonty** [comment]
Hi @irbrad, can you let me know which node version you're using? 

I originally tried the test above with node 0.12, but the komodo-debug package didn't actually work at all - no connection was made. I noticed a warning during installation of komodo-debug that said it was expecting node <= 0.10, so I uninstalled node and installed 0.10 instead. This got it working, and using your test script above I didn't run into any issues.

Thanks

**Comment by joonty** [comment]
In the interest of getting this version out the door, I'm going to assume it's the node version problem - someone else raised a similar issue (#223) which was down to the version.

However, please re-open this if it turns out it's due to something else.

Thanks
