### ISSUE TITLE
How to debug ruby program?

### ISSUE THREAD

**Issue by wusuopu** [joonty/vdebug#204]
It is easy to debug PHP with vdebug and xdebug.

I almost develop with ruby recently, and how to debug ruby with vdebug?

**Comment by joonty** [comment]
Hi @wusuopu,

Sorry that it's taken so long to get back to you. There is actually some documentation on debugging with ruby in the vim help file for vdebug. Run `:help VdebugSetUpRuby` to see it.

However, ruby is not as well supported as PHP, so you may run into some issues.

Thanks
