### ISSUE TITLE
Head scratching setting up Vdebug / xdebug

### ISSUE THREAD

**Issue by jrean** [joonty/vdebug#206]
Hi,

First of all, thank you for the hard work and this nice plugin!
I read the http://blog.joncairns.com/2015/01/looking-for-another-vdebug-maintainer/ and I hope you will find maintainer(s).

I will try to be as much precise as possible.
(I read all opened tickets as well as all closed and unfortunately I'm still stuck).
Here is my configuration and my env.

`I'm a Mac`
I run the following vim:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 28 2015 20:30:27)
MacOS X (unix) version
Included patches: 1-622
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +diff            +find_in_path    +jumplist        +mksession       +mouse_urxvt     +postscript      +signs           +tcl             +visual          +xim
+arabic          +cmdline_hist    +digraphs        +float           +keymap          +modify_fname    +mouse_xterm     +printer         +smartindent     +terminfo        +visualextra     -xsmp
+autocmd         +cmdline_info    +dnd             +folding         +langmap         +mouse           +multi_byte      +profile         -sniff           +termresponse    +viminfo         -xterm_clipboard
+balloon_eval    +comments        -ebcdic          -footer          +libcall         +mouseshape      +multi_lang      +python          +startuptime     +textobjects     +vreplace        -xterm_save
+browse          +conceal         +emacs_tags      +fork()          +linebreak       +mouse_dec       -mzscheme        -python3         +statusline      +title           +wildignore      -xpm
++builtin_terms  +cryptv          +eval            +fullscreen      +lispindent      -mouse_gpm       +netbeans_intg   +quickfix        -sun_workshop    +toolbar         +wildmenu
+byte_offset     +cscope          +ex_extra        -gettext         +listcmds        -mouse_jsbterm   +odbeditor       +reltime         +syntax          +transparency    +windows
+cindent         +cursorbind      +extra_search    -hangul_input    +localmap        +mouse_netterm   +path_extra      +rightleft       +tag_binary      +user_commands   +writebackup
+clientserver    +cursorshape     +farsi           +iconv           +lua             +mouse_sgr       +perl            +ruby            +tag_old_static  +vertsplit       -X11
+clipboard       +dialog_con_gui  +file_in_path    +insert_expand   +menu            -mouse_sysmouse  +persistent_undo +scrollbind      -tag_any_white   +virtualedit     -xfontset
```

I successfully installed Vdebug with Vundle. I can confirm because when I hit `<F5>` it outputs `Waiting for a connection (Ctrl-c to cancel, this message will self-destruct in 30 seconds...)`

I run a Laravel 5 PHP application. I use Homestead (a vagrant box) under VirtualBox. That means on the same machine (locally) I have my code on the host mirrored into the virtual machine, the guest. I edit the code with vim on the host.
So after reading the entire documentation this is what I did (baby steps):

- Control Xdebug is up and running!
On the virtual machine `php --ini` outputs ... `/etc/php5/cli/conf.d/20-xdebug.ini`.
If I perform a `phpinfo()` it tells me xdebug is installed `version 2.2.5`.

Directive | Local Value | Master Value
--------- | ----------- | ------------
xdebug.auto_trace | Off | Off
xdebug.cli_color | 0 | 0
xdebug.collect_assignments | Off | Off
xdebug.collect_includes | On | On
xdebug.collect_params | 0 | 0
xdebug.collect_return | Off | Off
xdebug.collect_vars	 | Off | Off
xdebug.coverage_enable | On | On
xdebug.default_enable | On | On
xdebug.dump.COOKIE | no value | no value
xdebug.dump.ENV | no value | no value
xdebug.dump.FILES | no value | no value
xdebug.dump.GET | no value | no value
xdebug.dump.POST | no value | no value
xdebug.dump.REQUEST | no value | no value
xdebug.dump.SERVER | no value | no value
xdebug.dump.SESSION | no value | no value
xdebug.dump_globals | On | On
xdebug.dump_once	 | On | On
xdebug.dump_undefined |Off | Off
xdebug.extended_info | On | On
xdebug.file_link_format | no value | no value
xdebug.idekey | no value | no value
xdebug.max_nesting_level | 100 | 100
xdebug.overload_var_dump | On | On
xdebug.profiler_aggregate | Off | Off
xdebug.profiler_append | Off | Off
xdebug.profiler_enable | Off | Off
xdebug.profiler_enable_trigger | Off | Off
xdebug.profiler_output_dir | /tmp | /tmp
xdebug.profiler_output_name | cachegrind.out.%p | cachegrind.out.%p
xdebug.remote_autostart | On | On
xdebug.remote_connect_back | Off | Off
xdebug.remote_cookie_expire_time | 3600 | 3600
xdebug.remote_enable | On | On
xdebug.remote_handler | dbgp | dbgp
xdebug.remote_host | localhost | localhost
xdebug.remote_log | no value | no value
xdebug.remote_mode | req | req
xdebug.remote_port | 9000 | 9000
xdebug.scream | Off | Off
xdebug.show_exception_trace | Off | Off
xdebug.show_local_vars | Off | Off
xdebug.show_mem_delta | Off | Off
xdebug.trace_enable_trigger | Off | Off
xdebug.trace_format | 0 | 0
xdebug.trace_options | 0 | 0
xdebug.trace_output_dir | /tmp | /tmp
xdebug.trace_output_name | trace.%c | trace.%c
xdebug.var_display_max_children | 128 | 128
xdebug.var_display_max_data | 512 | 512
xdebug.var_display_max_depth | 3 | 3

- Control and set `/etc/php5/cli/conf.d/20-xdebug.ini`
I edited the file based on what I read in the documentation.
__I'm aware something is probably wrong here!__
Is localhost the correct value?!
```
zend_extension=xdebug.so
xdebug.default_enable=1
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
xdebug.remote_autostart=1
xdebug.remote_host=localhost
xdebug.remote_connect_back=1
```

- Set the `path_maps` option.
As far as I understood I need to set this options. On the host I edit my code at `/Volumes/data/code/project-name` and on the guest the code is mirrored at `~/code/project-name`.
I set in my vimrc the following:
```
let g:vdebug_options['path_maps'] = {"/home/vagrant/code/project-name": "/Volumes/data/code/project-name"}
```

- I also installed the `Xdebug Helper chrome extension`.
__What should I put inside the IDE key select or custom option?__

--
This is pretty much all I did.
So now when I edit a file in vim and press `<F5>` it display the message he is waiting for a connection, so I refresh my script (controller) page but nothing happen and I receive a `no connection was made`.

Thank you in advance for your help.

--
Update!

This is what I found by enabling the log file:
Maybe it will help!
```
Log opened at 2015-04-10 17:49:18
I: Checking remote connect back address.
I: Remote address found, connecting to 192.168.10.1:9000.
E: Time-out connecting to client. :-(
Log closed at 2015-04-10 17:49:18
```

--
Update 2!

It works!! It took me half a day but it works :)
Thanks to the log.
I changed the `xdebug.remote_host` to `xdebug.remote_host=10.0.2.2` and disabled the `xdebug.remote_connect_back=0`.

I hope it will help someone one day. I will write a post to share with others.
:)

**Comment by jrean** [comment]
I guess we close the issue!

**Comment by joonty** [comment]
@jrean glad you got it working :) Sorry I missed like, all of it.

**Comment by dakruchko** [comment]
> I guess we close the issue!

Thanks, you just saved my day!
