### ISSUE TITLE
Breakpoint highlighting having different behaivours

### ISSUE THREAD

**Issue by ccolorado** [joonty/vdebug#208]
I get different breakpoint highlights and I don't understand why. 
Sometimes I get a '>' left of the line number and other times the complete line gets the background color changed. 

Also are the breakpoints highlight color defined by the theme or is there a way to override the colors used by vdebug? I get white text on bright green which is extremely hard to read.

**Comment by paprykarz** [comment]
Example vimrc lines for my 256 color xterm (I use white background and light Lucius Colorscheme):

	 if $TERM =~ '-256color$'
	 " ...
		highlight DbgBreakptLine ctermbg=113 ctermfg=244
		highlight DbgBreakptSign ctermbg=113 ctermfg=244
	 endif

**Comment by ccolorado** [comment]
oh, thanks for the tip. I still don't understand why sometimes it is just the the B> at the line number, but this sure helps.

**Comment by joonty** [comment]
@ccolorado sorry, I'm not sure why that's happening. Does it happen in the same session? I.e. does it happen to two breakpoints placed consecutively?

**Comment by ccolorado** [comment]
Havent used the debuger for a short while, however I did put this on my .vimrc.
but the plugin seem to override the settings.

```
highlight DbgBreakptLine ctermbg=none ctermfg=none
highlight DbgBreakptSign ctermbg=none ctermfg=10

highlight DbgCurrentLine ctermbg=none ctermfg=none
highlight DbgCurrentSign ctermbg=none ctermfg=red
```
I have to reload my .vimrc after starting vdebug, for those changes to take effect.

**Comment by joonty** [comment]
Ok, thanks for the info - I'll see if I can work out what's going on with this.

**Comment by joonty** [comment]
I believe I've fixed this issue in the `dev` branch, soon to be v1.5.0. Vdebug will now check to see if the highlights have been defined before defining them itself. Thanks

**Comment by ccolorado** [comment]
Awesome, thanks.
