### ISSUE TITLE
breakpoints, run to line, f5 nothing hit the location i want to stop into

### ISSUE THREAD

**Issue by OussamaDEV** [joonty/vdebug#211]
i did read the documetation, and everything goes well, but when i go to debug the project am working on (using laravel), i did set a breakpoint on a controller, i did refresh the page on the browser, the hit the route that instantiate the controller, the debug tab on vim is opened, but not where i want it to be, but inside the first script that get called when a new request is initiated (server.php).

i also did use `xdebug_break()` in many locations on my project, just for proof, but no result, always breaking on the first script file, i of course did run my project with `php-xdebug artisan serve --port 9494`, as suggested on the documentation, the ini file is configured properly, and a single normal script file is debugged with no problems at all.

i keep reading on the documentation script, script script ...; is that mean that vdebug can only be used with script files ?

please if anyone get the debugger to work on a larger project, with controller and modules, views, tel me how you did the setup, any ideas will be appreciated ?

**Comment by OussamaDEV** [comment]
ok :3, if anyone get into this problem, just hit f5, but still, why do i have to hit f5, why not just do it automatically, is it something like break on the first line when file include ? if so how can i disable it

**Comment by Taluu** [comment]
I guess you may be looking for the already existing option `break_on_open` ?
