### ISSUE TITLE
error no attribute 'set_breakpoint'

### ISSUE THREAD

**Issue by Kazanir** [joonty/vdebug#219]
Greetings! I believe I am having the same issue as the gentleman in #90, where I can't set a breakpoint at all due to a Python attribute error. Here is the relevant debugging info:

```
2.7.6 (default, Mar 22 2014, 23:03:41)
[GCC 4.8.2]
```

Vim version output:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:34)
Included patches: 1-52
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     +tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python          +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      +lua             +rightleft       +windows
+diff            +menu            +ruby            +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/usr/include/tcl8.6  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_LARGEFILE64_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector -L/usr/local/lib  -L/usr/lib/perl/5.18/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python2.7/config-x86_64-linux-gnu -lpython2.7 -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions  -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-1.9.1 -lpthread -lrt -ldl -lcrypt -lm  -L/usr/lib
```

**Comment by cincodenada** [comment]
Hi Kazanir, what version of vdebug are you using?  There should be a version number in the file header for `.vim/plugin/vdebug.vim` (or somewhere in `.vim/bundle` if you're using a plugin manager).

Could you also copy/paste the actual error message here, so we have the relevant line numbers and such?

**Comment by joonty** [comment]
@Kazanir if you can paste your Vdebug version number then we'll be able to take a closer look for you.

Thanks!

**Comment by ableeda** [comment]
Hello! I seem to be having the same issue. Very sad. I'm also not seeing anything when hitting F5, hitting F2 says 
"Not Connected"

I've been hitting a url in Chrome Version 45.0.2454.85 m that has
&XDEBUG_SESSION_START=vim
at the end of the url

inside vim, when I execute:
:Breakpoint

it gives me the following output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: Debugger instance has no attribute 'set_breakpoint'
Press ENTER or type command to continue


the top line of 
$ vim ~/.vim/bundle/vdebug/CHANGELOG 
=== Vdebug 1.5.1 / 2015-09-07

inside vim, :python print sys.version
2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

$ vim --version
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Apr  5 2012 10:17:30)
Included patches: 1-411
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval -browse ++builtin_terms +byte_offset +cindent 
-clientserver -clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+cryptv +cscope +cursorshape +dialog_con +diff +digraphs -dnd -ebcdic 
+emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path 
+float +folding -footer +fork() +gettext -hangul_input +iconv +insert_expand 
+jumplist +keymap +langmap +libcall +linebreak +lispindent +listcmds +localmap 
+menu +mksession +modify_fname +mouse -mouseshape +mouse_dec +mouse_gpm 
-mouse_jsbterm +mouse_netterm -mouse_sysmouse +mouse_xterm +multi_byte 
+multi_lang -mzscheme -netbeans_intg -osfiletype +path_extra +perl +postscript 
+printer +profile +python +quickfix +reltime +rightleft -ruby +scrollbind 
+signs +smartindent -sniff +startuptime +statusline -sun_workshop +syntax 
+tag_binary +tag_old_static -tag_any_white -tcl +terminfo +termresponse 
+textobjects +title -toolbar +user_commands +vertsplit +virtualedit +visual 
+visualextra +viminfo +vreplace +wildignore +wildmenu +windows +writebackup 
-X11 -xfontset -xim -xsmp -xterm_clipboard -xterm_save 
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall  -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64  -D_FORTIFY_SOURCE=1    -D_REENTRANT -D_GNU_SOURCE  -fstack-protector -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64  -I/usr/lib64/perl5/CORE  -I/usr/include/python2.6 -pthread   
Linking: gcc   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -o vim       -lselinux  -lncurses -lacl -lgpm   -Wl,-E -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lutil -lc -L/usr/lib64/python2.6/config -lpython2.6 -lutil -lm -Xlinker -export-dynamic 


from php -v 
PHP 5.3.20 (cli) (built: Dec 17 2014 15:34:51) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans

from php -i
xdebug

xdebug support => enabled
Version => 2.2.6
IDE Key => vim

Supported protocols => Revision
DBGp - Common DeBuGger Protocol => $Revision: 1.145 $

Directive => Local Value => Master Value
xdebug.auto_trace => Off => Off
xdebug.cli_color => 0 => 0
xdebug.collect_assignments => Off => Off
xdebug.collect_includes => On => On
xdebug.collect_params => 0 => 0
xdebug.collect_return => Off => Off
xdebug.collect_vars => Off => Off
xdebug.coverage_enable => On => On
xdebug.default_enable => On => On
xdebug.dump.COOKIE => no value => no value
xdebug.dump.ENV => no value => no value
xdebug.dump.FILES => no value => no value
xdebug.dump.GET => no value => no value
xdebug.dump.POST => no value => no value
xdebug.dump.REQUEST => no value => no value
xdebug.dump.SERVER => no value => no value
xdebug.dump.SESSION => no value => no value
xdebug.dump_globals => On => On
xdebug.dump_once => On => On
xdebug.dump_undefined => Off => Off
xdebug.extended_info => On => On
xdebug.file_link_format => no value => no value
xdebug.idekey => vim => vim
xdebug.max_nesting_level => 100 => 100
xdebug.overload_var_dump => On => On
xdebug.profiler_aggregate => Off => Off
xdebug.profiler_append => Off => Off
xdebug.profiler_enable => Off => Off
xdebug.profiler_enable_trigger => Off => Off
xdebug.profiler_output_dir => /tmp => /tmp
xdebug.profiler_output_name => cachegrind.out.%p => cachegrind.out.%p
xdebug.remote_autostart => Off => Off
xdebug.remote_connect_back => Off => Off
xdebug.remote_cookie_expire_time => 3600 => 3600
xdebug.remote_enable => On => On
xdebug.remote_handler => dbgp => dbgp
xdebug.remote_host => localhost => localhost
xdebug.remote_log => /tmp/xdebug_remote_log.xml => /tmp/xdebug_remote_log.xml
xdebug.remote_mode => req => req
xdebug.remote_port => 9000 => 9000
xdebug.scream => Off => Off
xdebug.show_exception_trace => Off => Off
xdebug.show_local_vars => Off => Off
xdebug.show_mem_delta => Off => Off
xdebug.trace_enable_trigger => Off => Off
xdebug.trace_format => 0 => 0
xdebug.trace_options => 0 => 0
xdebug.trace_output_dir => /tmp => /tmp
xdebug.trace_output_name => trace.%c => trace.%c
xdebug.var_display_max_children => 128 => 128
xdebug.var_display_max_data => 512 => 512
xdebug.var_display_max_depth => 3 => 3



from $ cat /tmp/xdebug_remote_log.xml
Log opened at 2015-09-10 17:51:09
I: Connecting to configured address/port: localhost:9000.
E: Could not connect to client. :-(
Log closed at 2015-09-10 17:51:09


$ cat /etc/redhat-release
CentOS release 6.5 (Final)

**Comment by BlackIkeEagle** [comment]
@ableeda could you list me the packages you have installed ?

so I can just take that list and install it in a box with centos 6.5 .

Keep in mind I'm not a centos user so I don't speak fluent yum :p

**Comment by Kazanir** [comment]
My recollection is fuzzy but I think I ended up fixing this by nuking and reinstalling all my Vim stuff. Sadly this makes me unable to contribute to tracking the problem down more precisely...

**Comment by BlackIkeEagle** [comment]
@ableeda I just did a clean install of vim, php-cli and xdebug to run a quick test. Everyting works for me, could you post your xdebug.ini and your vimrc here ?

I do understand correctly that you are debugging on localhost ?

**Comment by ableeda** [comment]
Thanks gang! Getting a gooder version of vim might be just the remedy. I downloaded something and it doesn't want to make. Will tweak it in the morning, and report all the details of note.

**Comment by BlackIkeEagle** [comment]
@ableeda When I did my test, my vim version installed from the centos 6.5 repo was the same version as you were using 7.2.411. So there might be an issue with your vim or xdebug config ?

**Comment by ableeda** [comment]
@BlackIkeEagle I wouldn't be surprised if the vim build is funky. Is there a suggested vim feature set to build with? 

Here is xdebug.ini
http://pastebin.com/eud3eCcN

**Comment by BlackIkeEagle** [comment]
@ableeda could you try to replace localhost with 127.0.0.1 in your xdebug.ini

and maybe reduce the xdebug options to a bare minimum and build up until it breaks ?

~~~
zend_extension="/usr/local/lib/php/extensions/no-debug-non-zts-20090626/xdebug.so"
xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
~~~

**Comment by BlackIkeEagle** [comment]
@ableeda Did you get it to work for you? If not, could you provide how your php was compiled?

**Comment by ableeda** [comment]
@BlackIkeEagle no luck yet, am trying to rebuild vim. The configuration options I went with are huge feature sets, enable ruby python and lua, disable X, disable GUI, leave most of the other things alone. I am running a virtual machine of centos 6.5 on a windows host machine, using oracle virtualbox, and connecting thru SecureCRT. Some day I hope to just dual boot linux on this machine. 

Running configure seemed to work:
https://gist.github.com/ableeda/563277d9cd5b1431c317

Make is not as happy:
https://gist.github.com/ableeda/72a6973d83a5c4d40ed3


I'll keep poking away at this, but here is a snapshot of what's happening so far.

**Comment by BlackIkeEagle** [comment]
@ableeda how is your vim built ? If it was built just with configure, then there is no python interpreter enabled so vdebug will not work.

**Comment by BlackIkeEagle** [comment]
@ableeda could you first try with the vim from CentOS? not custom vim?

**Comment by ableeda** [comment]
@BlackIkeEagle @Kazanir @joonty Ahhhh, it's working!!! Actually hit a breakpoint and got to stepping. Thanks for all of the help! Centos vim helped for sure, it also appears that secureCRT was capturing the F5 key, ended up adding the following to ~/.vimrc

map Q <F5>

**Comment by BlackIkeEagle** [comment]
@ableeda Fantastic, enjoy debugging php now :)

I'll close this one as fixed :+1:
