### ISSUE TITLE
The script could create pydbgp server

### ISSUE THREAD

**Issue by elvis-sik** [joonty/vdebug#220]
Hi.

I am trying vdebug out. My intention is only using it for Python. When I press F5 it searches for a connection for a while and then halts. If I do that and manually create a server (i.e., `python -S path/to/pydbgp -d localhost:9000 myscript.py`), it catches it. Is there a way to automatically create the server for debugging current file? I tried creating a function to do just that but wasn't able to.

Thank you very much!

**Comment by egalpin** [comment]
This is possible, but probably only desirable is a small number of cases. My recommendation would be to make an `alias` in `~/.bashrc` (or other shell, whatever you use) to make running a python script in debug mode easier.  By using an alias, you'll still be able to monitor any console output/print statements, which you'll lose using your proposed method.  To use the alias, open your script in Vim, then start `Vdebug`. In another terminal window, execute your alias like so:

      pydb ./my_script.py arg1 arg2

Here's the alias I use:

      alias pydb="python -S /path/to/pydbgp -k DEBUGGER_KEY -d localhost:9000 $@"


If you really want to do it all from a single terminal/Vim instance, keep reading :-)

Try adding this to your `.vimrc`:

      command! -nargs=* Pydb call Pydb( '<args>' )
      fu! Pydb(args)
          execute "!sleep 0.5 && python -S /path/to/pydbgp -k DEBUGGER_KEY -d localhost:9000 % ".a:args." &"
          execute "VdebugStart"
      endfunction

Then, map the function to <F5> (or other key, as desired):
If you don't need command line args for the script you're debugging:

      nnoremap <F5> :Pydb<CR>

If you __DO__ need command line args for the script:

      nnoremap <F5> :Pydb 

Command line args can then be provided to the `Pydb` function just like they would be to the python script itself.

__NOTES__:
1. Be sure that any spaces in your path are escaped with __two__ backslashes: `/path/to your/pydbgp` becomes `/path/to\\ your/pydbgp`
2. Be sure to use the correct DEBUGGER_KEY

Hope that helps! Let me know if you have questions.

**Comment by elvis-sik** [comment]
Thank you for your time and most thougthful answer!

**Comment by egalpin** [comment]
Happy to help out :-)
