### ISSUE TITLE
Feature Request: Break on include/require and like

### ISSUE THREAD

**Issue by hdon** [joonty/vdebug#221]
It would be useful to be able to set breakpoints on include/require/include_once/require_once.

Thanks!

**Comment by BlackIkeEagle** [comment]
Can you elaborate on this ?

Do you want to set the breakpoints manually and it does not work ?
Or do you want a setting to do automatic breakpoints on every {include,require}{,_once} ?

**Comment by BlackIkeEagle** [comment]
Is this a duplicate of #185 ?

**Comment by joonty** [comment]
Yep, @BlackIkeEagle this is a duplicate. I'll close and keep #185 as the issue for this. @hdon subscribe to that issue to keep up to date on developments.

Thanks
