### ISSUE TITLE
Feature Request -- VdebugTrace

### ISSUE THREAD

**Issue by egalpin** [joonty/vdebug#222]
Really like the `dev` branch feature of `VdebugTrace` :-) What would make it even more awesome would be:
1. The ability to manipulate the trace results in a similar manner as `DebuggerWatch`.  For example, expanding and collapsing PHP arrays to inspect elements.
2. The ability to add many variables to the Trace.  I know this is similar to the `DebuggerWatch`, but it allows for a specific group of variables to be watched rather than all locals.

Thanks for providing such an awesome tool!

**Comment by joonty** [comment]
@egalpin I like your ideas!

In the interest of getting 1.5.0 out the door I'm going to release the feature as it is (unless you find any bugs with it), but will port it in to version 2 and try and get your feature requests added to that.

I'll keep this open until then.

Thanks

**Comment by BlackIkeEagle** [comment]
This feature is available in the latest versions of vdebug
