### ISSUE TITLE
After exit from xdebug (by pressing F6) my F2 bind become broken

### ISSUE THREAD

**Issue by sergio-ivanuzzo** [joonty/vdebug#231]
I have own bind on F2 key (saving current file). After stop debugging pressing on F2 not work.
I also tried to ask on SO, but have not received any answer yet http://stackoverflow.com/questions/33947899/vim-after-exit-from-xdebug-command-binded-on-f2-not-work

Is it possible to fix this? And if possible, how can I do it?

**Comment by BlackIkeEagle** [comment]
@sergio-ivanuzzo A quick workaround could be for you to remap F2 used by vdebug to something else.

see: https://github.com/joonty/vdebug/blob/master/doc/Vdebug.txt#L979

**Comment by sergio-ivanuzzo** [comment]
got it. Thanks.
