### ISSUE TITLE
Breakpoint is being ignore in certain XDebug Sessions.

### ISSUE THREAD

**Issue by dkinzer** [joonty/vdebug#238]
Hello, thank you for vdebug:

I have a remote xdebug session for a PHP project that fails to stop at a break point when using vim with vdebug but not when using phpstorm on the same machine with the same xdebug settings (I would prefer to use vim).

The issue seems to be that vdebug assumes that the project root is at `/root/.composer/`  because there are some dependencies there that get connected to first.  However, the root of the project is actually `/var/www`.  In phpstorm there is a configuration to ignore certain folders.  And I can configure the session to essentially not stop at `/root/.composer` at all.

Yet, looking at the logs I can tell that vdebug does recognize the starting point, but then just some how forgets it:

```
- [Info] {Sat 20 2016 06:44:28} Searching for win by name /Users/dkinzer/projects/pluto/civic-1241-removes-hhs-merge-branches/docroot/includes/bootstrap.inc
- [Info] {Sat 20 2016 06:44:28} Win 1, name /Users/dkinzer/projects/pluto/civic-1241-removes-hhs-merge-branches/docroot/includes/bootstrap.inc
- [Info] {Sat 20 2016 06:44:28} Returning window number 1
- [Info] {Sat 20 2016 06:44:28} Found connection from ('192.168.99.100', 42030)
- [Debug] {Sat 20 2016 06:44:28} Command: feature_set -i 1 -n max_children -v 128
- [Debug] {Sat 20 2016 06:44:28} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="feature_set" transaction_id="1" feature="max_children" success="1"></response>
- [Info] {Sat 20 2016 06:44:28} Updated line number of breakpoint 11000 to 3183
- [Info] {Sat 20 2016 06:44:28} Registering 1 breakpoints with the debugger
- [Debug] {Sat 20 2016 06:44:28} Command: breakpoint_set -i 2 -t line -f file:///var/www/docroot/includes/bootstrap.inc -n 3183 -s enabled
- [Debug] {Sat 20 2016 06:44:28} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="2" state="enabled" id="3890001"></response>
- [Debug] {Sat 20 2016 06:44:28} Command: context_names -i 3
- [Debug] {Sat 20 2016 06:44:28} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="3"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context><context name="User defined constants" id="2"></context></response>
- [Debug] {Sat 20 2016 06:44:28} Available context names: {0: 'Locals', 1: 'Superglobals', 2: 'User defined constants'}
- [Debug] {Sat 20 2016 06:44:28} Command: step_into -i 4
- [Debug] {Sat 20 2016 06:44:28} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="step_into" transaction_id="4" status="break" reason="ok"><xdebug:message filename="file:///root/.composer/vendor/drush/drush/drush" lineno="112"></xdebug:message></response>
- [Info] {Sat 20 2016 06:44:28} Getting stack information
- [Debug] {Sat 20 2016 06:44:28} Command: stack_get -i 5
- [Debug] {Sat 20 2016 06:44:28} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stack_get" transaction_id="5"><stack where="{main}" level="0" type="file" filename="file:///root/.composer/vendor/drush/drush/drush" lineno="112"></stack></response>
- [Debug] {Sat 20 2016 06:44:28} Replacing remote path (/root/.composer) with local path (/Users/dkinzer/projects/.composer)
- [Debug] {Sat 20 2016 06:44:28} Replacing remote path (/root/.composer) with local path (/Users/dkinzer/projects/.composer)
- [Info] {Sat 20 2016 06:44:28} Moving to current position in source window
- [Info] {Sat 20 2016 06:44:28} Setting source file: /Users/dkinzer/projects/.composer/vendor/drush/drush/drush
- [Info] {Sat 20 2016 06:44:28} Placing pointer sign on line 112
- [Info] {Sat 20 2016 06:44:28} Getting Locals variables
- [Debug] {Sat 20 2016 06:44:28} Command: context_get -i 6 -c 0
- [Debug] {Sat 20 2016 06:44:28} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_get" transaction_id="6" context="0"><property name="$argv" fullname="$argv" address="139684477318704" type="array" children="1" numchildren="4" page="0" pagesize="128"><property name="0" fullname="$argv[0]" address="139684477318840" type="string" size="32" encoding="base64"><![CDATA[L3Jvb3QvLmNvbXBvc2VyL3ZlbmRvci9iaW4vZHJ1c2g=]]></property><property name="1" fullname="$argv[1]" address="139684477319112" type="string" size="14" encoding="base64"><![CDATA[LS1yb290PWRvY3Jvb3Q=]]></property><property name="2" fullname="$argv[2]" address="139684477319280" type="string" size="2" encoding="base64"><![CDATA[Y2M=]]></property><property name="3" fullname="$argv[3]" address="139684477319448" type="string" size="3" encoding="base64"><![CDATA[YWxs]]></property></property></response>
- [Info] {Sat 20 2016 06:44:28} Writing 5 properties to the context window
- [Debug] {Sat 20 2016 06:44:28} Writing to context window:
[ *Locals ] [ Superglobals ] [ User defined constants ]

- Locals at /Users/dkinzer/projects/.composer/vendor/drush/drush/drush:112

 ▾ $argv = (array [4])
  \
   ⬦ $argv[0] = (string [32]) `/root/.composer/vendor/bin/drush`
   |
   ⬦ $argv[1] = (string [14]) `--root=docroot`
   |
   ⬦ $argv[2] = (string [2]) `cc`
   |
   ⬦ $argv[3] = (string [3]) `all`
  /

- [Info] {Sat 20 2016 06:44:43} Running
- [Debug] {Sat 20 2016 06:44:43} Command: run -i 7
- [Debug] {Sat 20 2016 06:45:01} Closing the socket
- [Info] {Sat 20 2016 06:45:01} Connection to the debugger has been closed
```

**Comment by liamhendricks** [comment]
I'm having a similar problem ever since the new MacVim update. 

I set a breakpoint, F5 to start debugger, and refresh my localhost. The debugger begins normally and shows Status: break, Listening on :9000, Connected to [my host]. However, when I press F9 to jump to my breakpoint, Debugging Session ends unexpectedly. Status: stopped, Listening on: 9000, Not connected.

Right after I upgraded MacVim this morning, I got a similar error to this closed issue: https://github.com/joonty/vdebug/issues/93. I reinstalled MacVim with Homebrew and when I started mvim again the error was gone so I thought there might have been a symlink issue that was fixed by that. Maybe xdebug needs to be reinstalled?

**Comment by liamhendricks** [comment]
@dkinzer are you using xdebug with docker? I have discovered that my xdebug works on a normal mamp stack, but doesn't work with my docker stack. Could be an issue with php.ini.

**Comment by liamhendricks** [comment]
@dkinzer I fixed my issue, it might help you. In my .vimrc I put:
let g:vdebug_options["path_maps"] = { "/var/platform": "/Users/liam.hendricks/Sites/platform/poshdev/perfectly-posh-local/" }

**Comment by dkinzer** [comment]
@liamhendricks yes, I'm using xdebug with docker.  I already have path_maps configured in my .vimrc.  My issue seems to be different then yours.   In my case Break Points are respected, but only in the case where they happen in the dependent library that is getting called first.

I think I've seen my issue happen even when I wasn't using docker.  I had assumed it was not fixable until I saw that phpstorm handles the same situation gracefully.

is `/remote/root` a directory in your docker instance?

**Comment by liamhendricks** [comment]
@dkinzer No, it isn't, I was just using that as an example of the root directory. Sorry I wasn't able to help, but your post helped me diagnose my problem, so I thank you for that. As a fellow drupal developer, good luck :)

**Comment by andyr** [comment]
I see this occasionally as well and am not sure how to fix it.  But as a workaround, I just set breakpoints programmatically with:

`xdebug_break();`

**Comment by dkinzer** [comment]
@andyr thanks! that will be helpful.  I haven't had time to debug the issue further.

**Comment by dkinzer** [comment]
As it turns out the issue I'm running into happens because the `drush` command invokes a forked process.  And, vdebug fails to break because it cannot handle multiple debugging session.  Sadly the xdebug_break() idea does not seem to help in this case.

Closing since this is essentially an symptom of #227
