### ISSUE TITLE
vdebug no longer works after upgrading to kubuntu 16.04

### ISSUE THREAD

**Issue by evert** [joonty/vdebug#242]
Hi there!

I recently upgraded to kubuntu 16.04, and to my surprise, vdebug stopped working. Going through the troubleshooting I noticed that vdebug requires python support.

When I run `vim --version` it reports `+python3` but not `+python`. Will python3 work or do I really need `+python`. Installing the vim-gtk package unfortunately doesn't change much

if it's `+python` you need, at least I have something to investigate.

**Comment by evert** [comment]
Answering myself, I had to remove `vim-gtk` and `vim-gtk3` in order for `vim-gtk3-py2` to get picked up as the default. After doing this I get `+python` and `-python3` and this does fix the issue.

**Comment by jaimealsilva** [comment]
This worked for a while but now I'm trying with vim-gtk-py2 and vim-gtk2-py2 and :Vdebug* commands are gone again.

How can I diagnose? 

Thanks.

**Comment by tomeh** [comment]
@evert you can run the command `update-alternatives --config vim` and choose which version you want to run by default (vim-gtk3-py2)
