### ISSUE TITLE
Not working in Ubuntu 16.04

### ISSUE THREAD

**Issue by jaimealsilva** [joonty/vdebug#243]
I was really happy with my vim setup working my PHP projects until I updated my Ubuntu to 16.04. Now Vdebug commands are gone. I can see Vdebug help but that's it.

Have tried with gvim -V but throws a lot of info and couldn't redirect it to a file.

How can I diagnose what is happening?

Thanks.

**Comment by BlackIkeEagle** [comment]
@jaimealsilva From what I've heard you must install vim-gvim-py2, vdebug needs python2 and the default ubuntu gvim package only has python(3) enabled

**Comment by BlackIkeEagle** [comment]
@jaimealsilva see https://github.com/joonty/vdebug/issues/242

**Comment by jaimealsilva** [comment]
Thanks a lot!!!
