### ISSUE TITLE
Unable to run to breakpoint 

### ISSUE THREAD

**Issue by laserswald** [joonty/vdebug#245]
I'm running a PHP application locally and I have placed a breakpoint in a specific part of the application. Unfortunately, when I hit F5, Vdebug says the session has ended. I really don't want to single step through this massive application. 

Anyone have any ideas on how I can fix this?

**Comment by cincodenada** [comment]
Can you try debugging it after turning on logging [as detailed here](https://github.com/joonty/vdebug#debugging) and paste the log file?  Also, what OS are you running on?

**Comment by x-yuri** [comment]
I most likely experience this particular issue on Arch Linux (`php-7.0.6`, `xdebug-2.4.0`), and from `vdebug`'s log it seems like xdebug doesn't stop at breakpoint. When breakpoint is not in initial (starting) file that is. But I couldn't reproduce it with two files requiring each other. So to be more exact, when I set breakpoint in a laravel's controller, it doesn't stop at it.

**Comment by dave2309** [comment]
I have some similar behaviour. Localhost machine is Ubuntu 16.04. php 5.6.29, actualy xdebug works great using PhpStorm. The project is served through a vagrant box, which handle xdebug, nginx and php-fpm.
When in Vim i set up a breakpoint, it does not stop at it. On the xdebug log file on server side i have this:
Log opened at 2017-01-09 08:49:41
I: Connecting to configured address/port: 172.16.1.202:9000.
I: Connected to client. :-)
-> <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///srv/tomdeployer3.0/webroot/index.php" language="PHP" protocol_version="1.0" appid="13170" idekey="PHPStorm"><engine version="2.2.3"><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-2013 by Derick Rethans]]></copyright></init>

<- breakpoint_set -i 1 -t line -f file:///srv/tomployer3.0/webroot/index.php -n 27 -s enabled
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="breakpoint_set" transaction_id="1" state="enabled" id="131700004"></response>

<- context_names -i 2
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="context_names" transaction_id="2"><context name="Locals" id="0"></context><context name="Superglobals" id="1"></context></response>

<- run -i 3
-> <response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="run" transaction_id="3" status="stopping" reason="ok"></response>

Log closed at 2017-01-09 08:49:45

**Comment by rawaludin** [comment]
Missing this too. Based on what I read on vdebug docs, Breakpoint is only supported on active vdebug source window.

I same with the OP. In vscode, I usually place breakpoint on any part I want on my codebase, then xdebug will run till that point. Without showing detailed step I run before reaching that point.

**Comment by rawaludin** [comment]
Ignore my comment. Turn out this worked. But, by default it won't run till my breakpoint. I need to press F9 first to make it run till my breakpoint after vdebug started. Is there a way to make this default without pressing F9 key first?
