### ISSUE TITLE
Integrating PsySH into Vdebug

### ISSUE THREAD

**Issue by juampynr** [joonty/vdebug#246]
I would like to use http://psysh.org while I am debugging. It is possible to use it when I am debugging a command line script by running the following:

```
VdebugEval require('/usr/share/drush/vendor/psy/psysh/bin/psysh');
VdebugEval \Psy\sh()
```

The above activates the PsySH interpreter in the terminal where I executed the script. However, if I run these commands from a web request, I am unable to access the interpreter. Does anyone have any hints on where I should start looking at? I searched for how Vdebug evaluates code but I did not find anything useful there.

**Comment by DanielSiepmann** [comment]
As far as I understand PsySH, it's not possible to start it for web requests.

As mentioned here:
> Unfortunately, debugging through a webserver like Apache is not supported. However, we can debug our application using PHP’s embedded server:
https://www.sitepoint.com/interactive-php-debugging-psysh/

**Comment by BlackIkeEagle** [comment]
@juampynr  I think PsySH has its own place and goes beyond the scope of vdebug itself.
