### ISSUE TITLE
Ubuntu 16.04 + Vdebug

### ISSUE THREAD

**Issue by exussum12** [joonty/vdebug#249]
When running Vdebug in ubuntu 16.04 I need to use the py2 versions

Would it be possible to upgrade to py3 ? Imagine it may be a large upgrade ?

**Comment by verma-neeraj-in** [comment]
Really need this update. I switched to sublime till we get this update.

**Comment by exussum12** [comment]
You can install vim-nox-py2 which solves the issue.

**Comment by bitwombat** [comment]
Sure enough.  Can confirm this works on Ubuntu 16.04.  Weird, never had seen/heard of vim-nox-py2.  Note that it doesn't replace your vim installation, just puts a new binary in /usr/bin/vim.nox-py2.  Run that and Vdebug's alive again!

**Comment by josx** [comment]
Using debian with vim8 and same problem, it is compiled against python 3

**Comment by exussum12** [comment]
It looks harder to get python2 support for vim on debian. May have to compile yourself :(

**Comment by exussum12** [comment]
@bitwombat  you can use update-alternatives to make vim use vim-nox-py2 as default

**Comment by josx** [comment]
is it a big effort migrating vdebug from python 2 to python 3?

**Comment by BlackIkeEagle** [comment]
you can try python3 support in pr #271 . It will be added soonish
