### ISSUE TITLE
cant change f5 in .vimrc

### ISSUE THREAD

**Issue by schwrrring** [joonty/vdebug#250]
I am quite new to this and not sure if i get something fundamentally wrong.
I am not able to start the debugger beein able to open :help vdebug i guess i installed it (using vundle) successfully. Furthermore i added a shell script to my path: 

#!/bin/bash
export XDEBUG_CONFIG="idekey=xdebug"
/usr/bin/php "$@"

when adding 

  let g:vdebug_keymap['run'] = '<C-s>'       

 to my .vimrc to change from f5 to ctrl s 
  
it says:

E121: Undefined variable: g:vdebug_keymap 

What can i do to make it work ;)

**Comment by davidosomething** [comment]
add this line before it: `let g:vdebug_keymap = {}`

**Comment by schwrrring** [comment]
Hey David

thanks alot, that fixed it! 
Awsome, debugging works now.
thanks again.
best
