### ISSUE TITLE
VdebugLogFile is not documented

### ISSUE THREAD

**Issue by DanielSiepmann** [joonty/vdebug#255]
The option is mentioned in the docs introduced at https://github.com/joonty/vdebug/commit/2c375b3219fe86b1dea2a36a46859583ee605b6f .
But the tag does not exist.

The defaults can be found at https://github.com/joonty/vdebug/blob/master/plugin/vdebug.vim#L93

**Comment by lucc** [comment]
close?

**Comment by DanielSiepmann** [comment]
Thanks you :)

Looks like I didn't took a closer look as it already was there.
