### ISSUE TITLE
BreakpointWindow open by default?

### ISSUE THREAD

**Issue by nathanielks** [joonty/vdebug#260]
Heya!

I was wondering if it were possible for the BreakpointWindow to be open by default? Somewhat related, perhaps there's a way to customize the layout when the debugging session begins?

**Comment by BlackIkeEagle** [comment]
@nathanielks Personally I don't think you want to loose additional screenspace by opening the BreakpointWindow by default.

The layout is now hardcoded if I remember correctly so if that would become customizable then you probably could add the BreakpointWindow there if you want it.

**Comment by BlackIkeEagle** [comment]
With the latest master you can do this, you could add the following to your `.vimrc` for example:

```
" vdebug settings
let g:vdebug_options = {
    \'path_maps': {'/phpapp': getcwd()},
    \"window_arrangement" : ["DebuggerWatch", "DebuggerStack", "DebuggerStatus", "DebuggerBreakpoints"]
\}
```

**Comment by nathanielks** [comment]
Hey, hey! This is great! Thanks, @BlackIkeEagle!
