### ISSUE TITLE
Question:No connection was made

### ISSUE THREAD

**Issue by zjhxmjl** [joonty/vdebug#266]
hey,i start vdebug on local machine,but get this error info:No connection was made
1,my os:fedora 20
2,/etc/php.ini
`xdebug.remote_enable=1
xdebug.remote_host=localhost
xdebug.remote_port=9000`
3,.vimrc
`let g:vdebug_options = {}
let g:vdebug_options["port"] = 9000
let g:vdebug_options["break_on_open"] = 0  `
when i run the test.php from terminal with the command: php test.php ,it's ok! so i think xdebug configuration is right,please give me some suggestion,thks!
![2017-03-03-130907_778x445_scrot](https://cloud.githubusercontent.com/assets/4043922/23539047/574a612e-0013-11e7-8dc9-313f80c96139.png)

**Comment by BlackIkeEagle** [comment]
do you have your xdebug env vars set for your cli script?

XDEBUG_CONFIG="remote_host=127.0.0.1" php test.php

**Comment by zjhxmjl** [comment]
sorry,do you mean i must add the xdebug env in .bashrc or others? can 
you give me a configuration guide for vdebug on linux? thks

**Comment by BlackIkeEagle** [comment]
No just do

~~~ sh
$ XDEBUG_CONFIG="remote_host=127.0.0.1" php test.php
~~~

**Comment by zjhxmjl** [comment]
yeah,it's ok!but i vi test.php and run F5,why i get this "No connection 
was made" info?

**Comment by BlackIkeEagle** [comment]
xdebug could not connect to vdebug it would seem

could you add your xdebug.ini, and did you add custom vdebug config?

**Comment by zjhxmjl** [comment]
i only do this step:
edit /etc/php.ini and add this:
|xdebug.remote_enable=1 xdebug.remote_host=localhost 
xdebug.remote_port=9000|
edit .vimrc and add this:
|let g:vdebug_options = {} let g:vdebug_options["port"] = 9000 let 
g:vdebug_options["break_on_open"] = 0|

**Comment by BlackIkeEagle** [comment]
could you paste the output of:

php -m

**Comment by zjhxmjl** [comment]
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xdebug
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]
Xdebug

**Comment by BlackIkeEagle** [comment]
could you test with default vdebug configuration, so whithout any overrides in your .vimrc

**Comment by zjhxmjl** [comment]
thks,i add url /?XDEBUG_SESSION_START=1 and solved!:-D /
