### ISSUE TITLE
DebuggerWatch all closed/open by default feature request.

### ISSUE THREAD

**Issue by danshumaker** [joonty/vdebug#269]
Sometimes I get a ton of variables being expanded in my DebuggerWatch window. And of those variables I'd like to only see or watch a few.   Is there a option to automatically close all expanded variable trees by default? If not could we add one please?

Otherwise, we'll be trying to implement hacky things like this:
https://stackoverflow.com/questions/25495869/vdebug-expand-all-variable-trees/42860032#42860032

Which I almost got working.

But it would be great to have it as an option.

Or even better, is there a way to just watch singular variables?

**Comment by BlackIkeEagle** [comment]
This is available in the latest versions of vdebug `:VdebugTrace`
