### ISSUE TITLE
No Commands show up in neovim

### ISSUE THREAD

**Issue by micalexander** [joonty/vdebug#294]
I would imagine that this plugin supports neovim as it is pretty much vim. When I run `:help Vdebug` I am presented with help. However none of the Vdebug commands even show up in command mode even when typing `:V<tab>`

I am running alpine linux with neovim and python3 support.

Any ideas?

**Comment by lucc** [comment]
Are you on master or on v2-integration? What kind of commands do you see in the help file?

I am on v2-integration and I can complete `VdebugEval`,  `VdebugOpt`, `VdebugStart` and `VdebugTrace`.

**Comment by micalexander** [comment]
I have switched to the v2-integration branch and I still seem to have the same problem. I can see all the commands in help just not able to complete them or access them as commands

```
E492: Not an editor command: VdebugStart
```

**Comment by lucc** [comment]
Can you check `:scriptnames` if you have multible versions of vdebug installed? Maybe it is loaded from an unexpected location.

**Comment by micalexander** [comment]
this seems to be all I see for it.

~/.config/nvim/.cache/init.vim/.dein/plugin/vdebug.vim

**Comment by micalexander** [comment]
So it seems that it was because I only had support for python 3 and not python 2. Adding support for python 3 fixed it.
