### ISSUE TITLE
Not setting breakpoints correctly

### ISSUE THREAD

**Issue by ndench** [joonty/vdebug#299]
I've just installed Vdebug and trying to get it set up using xdebug on my small Symfony3 app, only problem I'm having is that it doesn't seem to be setting the breakpoints.

My project is running in a vagrant vm on ubuntu 16.04.

If I have `vdebug_options["break_on_open"] = 1` then it will break, but then pressing f5 will just finish the session, no matter how many breakpoints I have set. I can use `xdebug_break()` and it breaks correctly though.

I've tried setting `vdebug_options["path_maps"]` but it doesn't seem to make a difference.
I checked my python versino with `:python import sys; print(sys.version)`:
```
2.7.13 (default, Jul 21 2017, 03:24:34)
```

I also have python3 installed, not sure if this is a problem?
```
:python3 import sys; print(sys.version)
3.6.2 (default, Jul 20 2017, 03:52:27)
```

I've been using the debugger in PhpStorm for ages and it works fine.

Is there anything else I can try to track this problem down?

**Comment by BlackIkeEagle** [comment]
@ndench I'm sorry I'm not entirely sure what the problem is. First suspect is indeed that the path_maps are not correct. Could you possibly describe a minimal test scenario that reproduces your issue?
