### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by arcseldon** [joonty/vdebug#308]
See little or no pulse, and 50+ open issues. 

Is this project still being actively maintained?

Thanks for any clarifications.

**Comment by BlackIkeEagle** [comment]
when there is time people are working on it to get to v2, see v2-integration branch. the 1.x version works just fine for most people, you are only fucked when using ubuntu where they have dropped python2 support from their vim packages.

v2-integration will eventually move to python3 but it heavyly depdends on free time to get it done
