### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by yriveiro** [joonty/vdebug#311]
Hi.

There is a version 2.x with some improvements and a project board, but I see many opened pull requests and issues without response.

Is this project abandoned?

Regards

**Comment by BlackIkeEagle** [comment]
No, but sometimes life and other things are important and take time.

**Comment by jeromedalbert** [comment]
I thought the same, but you should have a look branch `v2-integration`, it has all the latest goodies

**Comment by BlackIkeEagle** [comment]
Going to close this because the project is not abandoned :)
