### ISSUE TITLE
'NoneType' object has no attribute 'step_into' with Python 3 support

### ISSUE THREAD

**Issue by letharion** [joonty/vdebug#317]
Trying out v2-integration to get python 3 support, I can get the debugger to run and break, but as soon as I try to step, I get

`'NoneType' object has no attribute 'step_into'`

More details:

> Vdebug will wait for a connection in the background
> Found connection, starting debugger
> Debugging session has ended
> Vdebug will wait for a connection in the background
> An error occured: <class 'AttributeError'>^@Traceback (most recent call last):^@  File "/home/letharion/.vim/pythonx/vdebug/event.py", line 524, in dispatch_event^@    Dispatcher.events[name](self.__session_handler).run(*args)^@  File "/home/letharion/.vim/pythonx/vdebug/event.py", line 331, in run^@    res = self.api.step_into()^@AttributeError: 'NoneType' object has no attribute 'step_into'

It's also interesting to note that when the debugger starts and the debuggerwatcher opens, it says `Status: listening
Listening on: 9000
Not connected`

I don't have a working setup with older versions anymore, but I don't think it should say "Not connected" once those splits open up?

**Comment by BlackIkeEagle** [comment]
@letharion can you describe how you got this error, what language were you debugging?

And also important, is the issue still present in the last version of v2-integration?

**Comment by letharion** [comment]
@BlackIkeEagle Today I cloned vdebug, switched to v2-integration, and copied the plugin directory into my ~/.vim, I'm on e37e43509778d167af139b9879d329fdb944abbc

I have a PHP-based API, running under apache.
I hit F10, get visual confirmation on breakpoint, F5, and get `Vdebug will wait for a connection in the background`.
When curl hits the API, initially, nothing happens. The request doesn't finish, but neither does vim appear to react.
When I hit F5 again, I get
"Found connection, starting debugger
Debugging session has ended
Vdebug will wait for a connection in the background"
The 4 splits open up though, so it looks like I'm in the debugger.

Status is now "listening", and I get a "Vdebug will wait for a connection in the background" message. The next curl request is patiently waiting for a response, so it appears a connection has been established. Trying F2, I now get

"An error occured: <class 'AttributeError'>^@Traceback (most recent call last):^@  File "/home/letharion/.vim/pythonx/vdebug/event.py", line 524, in dispatch_event^@    Dispatcher.events[name](self.__session_han
dler).run(*args)^@  File "/home/letharion/.vim/pythonx/vdebug/event.py", line 322, in run^@    res = self.api.step_over()^@AttributeError: 'NoneType' object has no attribute 'step_over'
Found connection, starting debugger
Debugging session has ended
Vdebug will wait for a connection in the background"

The next curl request finishes right away, so I send another one, which ends up waiting.
Trying F4 now, I get
"An error occured: <class 'AttributeError'>^@Traceback (most recent call last):^@  File "/home/letharion/.vim/pythonx/vdebug/event.py", line 524, in dispatch_event^@    Dispatcher.events[name](self.__session_han
dler).run(*args)^@  File "/home/letharion/.vim/pythonx/vdebug/event.py", line 340, in run^@    res = self.api.step_out()^@AttributeError: 'NoneType' object has no attribute 'step_out'
Found connection, starting debugger
Debugging session has ended
Vdebug will wait for a connection in the background"

**Comment by BlackIkeEagle** [comment]
@letharion I cannot reproduce this.

Following steps were taken:
.vimr with minimal config:
```
set nocompatible

" vdebug settings
let g:vdebug_options = {
    \'path_maps': {'/phpapp': getcwd()}
\}
```

checked out latest v2-integration in ~/devel/vdebug
then:
```
$  rm -rf .vim
$ mkdir .vim
$ cp -a ~/devel/vdebug/*"./.vim/
```

open vim in a php project, press F5, debugging was already enabled via a browser plugin, refresh page, vdebug successfully works.

**Comment by jimafisk** [comment]
I thought I had resolved my issue by simplifying the vdebug configuration in my `~/.vimrc`:
```
"DEBUGGING:
"----------
let g:vdebug_features = { 'max_children': 256 }
let g:vdebug_options={}
let g:vdebug_options['break_on_open'] = 0
```
It worked for a little bit, but I seem to be back to square one again. Sometimes it would run if I detached with <kbd>F7</kbd> but now doing that gives me the following error:

```
An error occured: <class 'AttributeError'>^@Traceback (most recent call last):^@  File "/root/.vim/bundle/vdebug/python3/vdebug/event.py", line 522, in dispatch_event^
@    Dispatcher.events[name](self.__session_handler).run(*args)^@  File "/root/.vim/bundle/vdebug/python3/vdebug/event.py", line 493, in run^@    self.session.detach()
^@  File "/root/.vim/bundle/vdebug/python3/vdebug/session.py", line 229, in detach^@    self.__api.detach()^@AttributeError: 'NoneType' object has no attribute 'detach
'^@
```

I was also setting a breakpoint in a generic place (`modules/block/block.module`) to test and it appears that code was not being run. Setting a breakpoint in the front end theme (`core/themes/bartik/bartik.theme`) or another core module (`core/modules/user/user.module`) worked - just in case someone else's issue is simply setting a breakpoint somewhere that isn't being executed.

**Comment by jimafisk** [comment]
It doesn't work consistently for me, but when it does work these are the steps:
1. Set the breakpoint with <kbd>F10</kbd> then start the debugger with <kbd>F5</kbd>
2. Go to the browser and refresh the page (this will finish and _not_ continue refreshing)
3. Go back to the editor and see that the debugger windows have popped up but the `DebuggerStatus` says "Not connected" 
4. Press <kbd>F7</kbd> to detach (the `'NoneType' object has no attribute 'detach'` errors will appear)
5. Press any key to continue and `Found connection, starting debugger` message appears
6. Press any key again and then you can continue with a normal debugging session (note your browser will not still be reloading)

Also possibly related: https://github.com/vim-vdebug/vdebug/issues/90
