### ISSUE TITLE
Can't remove / set breakpoints if vdebug is not running after being run once

### ISSUE THREAD

**Issue by Taluu** [joonty/vdebug#319]
Setting some breakpoints and removing them is easy, before running vdebug (through `F5`)... but once it launched and stopped, we have the message "vdebug is not running".

I think this is due to the async listening, but I'm not too sure ?

I'm using nvim 0.2 on the v2-integration branch.

**Comment by BlackIkeEagle** [comment]
Thanks for reporting thisone, the issue is now resolved in v2-integration
