### ISSUE TITLE
Can't get vdebug working with neovim v0.2.2

### ISSUE THREAD

**Issue by meirege** [joonty/vdebug#324]
Hi,

I have been trying to get vdebug to work with my neovim installation (v0.2.2) but I can't seem to get it working...

All my other plugins seems to work fine after switching from vim to neovim though... I think it has something to do with python support, but can't figure it out...

When I run `:echo has('python')` it returns 0 however.

Can anybody help me out?

**Comment by lucc** [comment]
Check the official docs for python+neovim: https://neovim.io/doc/user/provider.html#provider-python

**Comment by meirege** [comment]
I tried this but to no succes...   I also have a python version installed through my MAMP installation apparently... Could this be the problem?

I did both install commands like `pip2 install --upgrade neovim `. 
neovim keeps giving 0 when I try `:echo has('python')`

**Comment by lucc** [comment]
I have no idea what MAMP is. But it sounds like a problem with neovim+python2 and whatever platform you use. It is not per se an issue with vdebug as vdebug *requires* `:echo has('python')` to print `1`. Before that we can most likely not help you.

**Comment by meirege** [comment]
Thank you, your answer pointed me to https://github.com/neovim/neovim/issues/2193 which solved my issue.
