### ISSUE TITLE
Vdebug + Neovim buffer target error

### ISSUE THREAD

**Issue by SamuelTissot** [joonty/vdebug#325]
Hello, and huge thanks for the great work, I use vdebug everyday (almost) :)

As of today however vdebug became unusable on neovim ( v0.2.2)

**NOTE:** it still works with macvim

steps to reproduce
-----
1. set `break_on_open` option to `1` (tested with 0 - same result)
2. start the debugger <F5> 
3. reload the page in browser

behavior
-----
1. The debugger seems to "break" at the first line. however none of the vdebug buffers are open. and the message stays as: `Waiting for a connection (Ctrl-C to cancel, this message will self-destruct in  20  seconds...)`
2. none of the F key are working.
3. when I press `Ctrl-C` I get this error message.
```
Connection has been closed
An error occured: <class 'neovim.api.nvim.NvimError'>
Traceback (most recent call last):
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 174, in run
    self.open()
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 47, in open
    self.ui.open()
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 79, in open
    raise e
NvimError: Keyboard interrupt
```
4. I notice that it created a new buffer in a new tab for the file I was trying to debug.

![screen shot 2018-02-23 at 1 23 15 pm](https://user-images.githubusercontent.com/11725094/36610420-2d190d8e-189e-11e8-88b8-c00c668a011e.png)

5. Will the debugger is running I cannot switch to this buffer

Additional info
----
I rolled back to release tag v1.5.1, but I still got the behavior.
python is enable `echo has("python3")` = `1`

sometime the `DebuggerWatch` buffer is shown after I `<C-c>` 

I have done and follow the instruction in #188 
I suspect It is a duplicate of #305 but I tried [reafle fork](https://github.com/reafle/vdebug) and I get the same issue

vdebug.log
---
```
- [Info] {Fri 23 2018 10:31:12} Closing the connection
- [Debug] {Fri 23 2018 10:31:12} Command: stop -i 1
- [Debug] {Fri 23 2018 10:31:12} Response: <?xml version="1.0" encoding="iso-8859-1"?>
<response xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" command="stop" transaction_id="1" status="stopped" reason="ok"></response>
- [Debug] {Fri 23 2018 10:31:12} Closing the socket
- [ERROR] {Fri 23 2018 10:31:12} An error occured: <class 'neovim.api.nvim.NvimError'>
Traceback (most recent call last):
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/start_vdebug.py", line 31, in run
    self.runner.run()
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 184, in run
    self.open()
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/vdebug/runner.py", line 48, in open
    self.ui.open()
  File "/Users/samuel.tissot/.vim/bundle/vdebug/plugin/python/vdebug/ui/vimui.py", line 79, in open
    raise e
NvimError: Keyboard interrupt
```

**Comment by SamuelTissot** [comment]
Update:
The issue seems to be on my side. I clone the exact repo in another folder and. **it works**. 
Same code, different folder and different behaviour. Is there a cache somewhere that I do not know about?

**Comment by SamuelTissot** [comment]
Update: if I do a
`mv project/root newproject/root`

the debugger works. So it really seems like some kind of caching, I suspect with the `path_mapping` and/or nvim.

any help/pointers on this issue would be greatly appreciated.

thanks

**Comment by BlackIkeEagle** [comment]
@SamuelTissot I think this is fixed in v2, you will be able to update soon

**Comment by SamuelTissot** [comment]
@BlackIkeEagle thanks

In the mean time for everyone experiencing the issue just rename your project root folder.
