### ISSUE TITLE
Watch Variables

### ISSUE THREAD

**Issue by tanzhou007** [joonty/vdebug#64]
It would be so helpful if we can type a command to setup a watched variable so it will always appear on the top of the variable's window.

**Comment by marter** [comment]
Any update on this one? Thanks for all the work!

**Comment by juampynr** [comment]
Isn't this the new :Trace method? If so, shall we close this?

https://github.com/joonty/vdebug/pull/178

**Comment by BlackIkeEagle** [comment]
this is indeed the `:VdebugTrace` command, closing
