### ISSUE TITLE
Can't "step in" the property of a multi-dimensional array in PHP

### ISSUE THREAD

**Issue by hobbes3** [joonty/vdebug#83]
I'm using the dev branch of vdebug (1337237) and Xdebug v2.2.1 (PHP 5.4.14). I'm running MacVim Custom Version 7.3 (66).

I am inspecting a big PHP array of a database return query. The array length is 1979 (correspond to the 1979 rows), and the 2nd dimension of the array has 14 keys (correspond to the 14 columns of the table).

I'm not sure the exact circumstance but when the array gets big, you can't double-click or press enter to "step in" to the array's next dimension.

I hope the screenshot will be make it more clearer:

I can't double click `$retval[0]`
![screen shot 2013-05-10 at 1 52 53 pm](https://f.cloud.github.com/assets/1494403/489416/937f8984-b99b-11e2-9355-734c0b853b4b.png)

But if I select `$retval[0]` and type `<Leader>e`, then I can view its content:

![screen shot 2013-05-10 at 1 53 12 pm](https://f.cloud.github.com/assets/1494403/489423/be0c056a-b99b-11e2-9561-00f22712f86e.png)

I originally though this was a limitation to Xdebug's default variable viewing configuration, but I set everything to max. Here is my Xdebug config in `php.ini`:

```
xdebug.remote_enable=on
xdebug.remote_autostart=1
xdebug.remote_handler=dbgp
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_log="/usr/local/var/log/xdebug.log"
xdebug.var_display_max_data=-1
xdebug.var_display_max_children=-1
xdebug.var_display_max_depth=-1
```

**Comment by BlackIkeEagle** [comment]
this issue is fixed a while ago in vdebug
