### ISSUE TITLE
Formatting issue with exception in watch window

### ISSUE THREAD

**Issue by qstrahl** [joonty/vdebug#91]
I noticed this malformed output during a debug session, with a [partial] stack trace apparently showing up in the middle of an Exception object's properties:

![2013-06-10-135400_1918x1060_scrot](https://f.cloud.github.com/assets/2235277/633207/3e53717c-d1f7-11e2-8db3-86f784135e41.png)

Further inspection revealed the text to be from the Exception's `xdebug_message` property, as illustrated here:

![2013-06-10-135414_1918x1060_scrot](https://f.cloud.github.com/assets/2235277/633208/40ce1178-d1f7-11e2-9fc7-4e08e29e62a6.png)

Not sure of the cause.

**Comment by joonty** [comment]
I've reproduced the case of raising a catchable fatal error as an ErrorException, several levels deep in the stack, but I don't get an `xdebug_message` that has weird truncation issues in the same way. @qstrahl it really depends on how much you care, but if you can still reproduce it could you supply a log file? If not, I'll close.

Thanks
